#!/usr/bin/env bash
# Pull the webfonts into assets/fonts/ and generate assets/css/fonts.css,
# so the site makes no third-party request at all.
#
#   deploy/fetch-fonts.sh
#
# Re-run it to update; it is deterministic and safe to repeat.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/assets/fonts"
CSS="$REPO/assets/css/fonts.css"
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36'
API='https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;1,400&family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Serif:ital,wght@0,400;0,500;1,400&display=swap'

mkdir -p "$OUT"
raw="$(curl -sL --max-time 60 -A "$UA" "$API")"
[ -n "$raw" ] || { echo "could not reach Google Fonts" >&2; exit 1; }

{
  echo "/* Self-hosted webfonts. GENERATED by deploy/fetch-fonts.sh — do not edit."
  echo "   The site makes no third-party request; nothing about a visitor reaches"
  echo "   Google, which is what lets the privacy page say what it says. */"
  echo
} > "$CSS"

# Keep only the latin and latin-ext blocks; the rest is dead weight for this site.
python3 - "$raw" "$OUT" "$CSS" <<'PY'
import re, sys, os, subprocess, hashlib

raw, out, cssfile = sys.argv[1], sys.argv[2], sys.argv[3]
blocks = re.findall(r'/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})', raw, re.S)
kept, seen = [], set()

for subset, block in blocks:
    if subset not in ('latin', 'latin-ext'):
        continue
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
    fam = re.search(r"font-family:\s*'([^']+)'", block)
    wgt = re.search(r'font-weight:\s*(\d+)', block)
    sty = re.search(r'font-style:\s*(\w+)', block)
    if not (url and fam):
        continue
    name = '%s-%s-%s-%s.woff2' % (
        fam.group(1).replace(' ', ''), wgt.group(1) if wgt else '400',
        sty.group(1) if sty else 'normal', subset)
    path = os.path.join(out, name)
    if name not in seen:
        seen.add(name)
        if not os.path.exists(path) or os.path.getsize(path) == 0:
            subprocess.run(['curl', '-sL', '--max-time', '60', url.group(1), '-o', path], check=True)
    # the source already carries format('woff2'); swap the URL only
    block = block.replace(url.group(1), '../fonts/%s' % name)
    if 'font-display' not in block:
        block = block.replace('@font-face {', '@font-face {\n  font-display: swap;')
    kept.append('/* %s — %s */\n%s' % (fam.group(1), subset, block))

with open(cssfile, 'a') as f:
    f.write('\n\n'.join(kept) + '\n')

total = sum(os.path.getsize(os.path.join(out, n)) for n in seen)
print('%d font files, %.0f KB total' % (len(seen), total / 1024))
PY

echo "wrote $CSS"
