#!/usr/bin/env node
/* ============================================================
   TMUA Lab — build the past-paper bank.  `node tools/build-past.js`

   Reads every data/past/YYYY-PN.json transcription, checks each
   answer against the official key in data/past/answer-keys.json,
   and emits assets/js/bank-past.js.

   Transcriptions live as JSON so a long transcription run is
   durable and diffable; this file is generated, never edited.
   ============================================================ */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'data', 'past');

const KEYS = JSON.parse(fs.readFileSync(path.join(DIR, 'answer-keys.json'), 'utf8'));
const LETTERS = 'ABCDEFGH';

const files = fs.readdirSync(DIR)
  .filter(f => /^\d{4}-P[12]\.json$/.test(f))
  .sort();

let all = [], errors = 0, byPaper = [];

for (const f of files) {
  const tag = f.replace('.json', '');                 // e.g. 2023-P1
  const [year, pp] = tag.split('-');
  const paper = +pp.slice(1);
  const key = KEYS[tag];
  if (!key) { console.error(`  ERROR ${tag}: no official answer key`); errors++; continue; }

  const qs = JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8'));
  for (const q of qs) {
    const n = q.n;
    const expected = key[n - 1];
    const got = LETTERS[q.a];
    if (!(n >= 1 && n <= 20)) { console.error(`  ERROR ${tag} Q${n}: number out of range`); errors++; continue; }
    if (got !== expected) {
      console.error(`  ERROR ${tag} Q${n}: marked ${got}, official key says ${expected}`);
      errors++; continue;
    }
    if (q.a >= q.o.length) { console.error(`  ERROR ${tag} Q${n}: answer index past the options`); errors++; continue; }
    all.push({
      id: `PP-${year}-P${paper}-Q${String(n).padStart(2, '0')}`,
      p: paper, t: q.t, sp: q.sp, d: q.d,
      src: { year: +year, paper: paper, number: n },
      sol: q.sol || 'lab',
      fig: q.fig || undefined,
      q: q.q, o: q.o, a: q.a, e: q.e
    });
  }
  byPaper.push(`${tag} ${qs.length}/20`);
}

const body = all.map(q =>
  '  q(' + JSON.stringify(q, null, 2).replace(/\n/g, '\n  ') + ');'
).join('\n\n');

const out = `/* ============================================================
   TMUA Lab — past-paper bank.  GENERATED by tools/build-past.js.
   Edit data/past/*.json, not this file.

   Questions transcribed from the past papers UAT-UK publishes as
   candidate preparation material. Every answer below has been
   checked against the official answer key at build time.
     sol: 'lab'      — solution written for this site
     sol: 'official' — condensed from UAT-UK's worked answers
   ============================================================ */
(function (root) {
  'use strict';
  var TL = (root.TL = root.TL || {});
  var B = (TL.BANK = TL.BANK || []);
  function q(o) { B.push(o); }

${body}

})(window);
`;

fs.writeFileSync(path.join(ROOT, 'assets', 'js', 'bank-past.js'), out);

console.log(`bank-past.js: ${all.length} questions from ${files.length} paper(s)`);
console.log('  ' + (byPaper.join(', ') || 'none yet'));
const done = new Set(files.map(f => f.replace('.json', '')));
const todo = Object.keys(KEYS).filter(k => !done.has(k)).sort();
console.log(`  remaining: ${todo.length ? todo.join(' ') : 'none — all papers transcribed'}`);
if (errors) { console.error(`\n${errors} answer(s) disagree with the official key`); process.exit(1); }
